### ISSUE TITLE
ERROR: s3 upload was failed: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by sysdef** [pfig/net-amazon-s3#56]
S3 Access in Frankfurt is not working.

In the AWS Docs it states that every new region after Jan 30, 2014 will only support AWS Signature V4:
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

When will Net::Amazon::Signature::V4 be implemented in Net::Amazon::S3?

**Comment by rustyconover** [comment]
This isn't too hard, it is just getting the code merged.  Personally I'd use AWS::Signature4.

**Comment by robin13** [comment]
+1 for getting this fixed!

**Comment by rustyconover** [comment]
This is a bit tougher than anticipated.  This is what I learned from a few hours of hacking of trying to replace the entire signature mechanism with AWS-Signature4

v4 authentication requires that the entire body have a SHA256 checksum applied to it before the request is sent to S3.  Right now with v2 authentication we don't need to do that.  The Net::Amazon::S3 constructs HTTP::Request object with coderef's that determine the body to be sent.  We can't calculate the checksum because have to load and buffer loading the original file's entire content into memory and we can't rewind coderefs.

This is best explained at the bottom part of this page:

http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

There is an alternative to load the content to the server in chunks, which is probably how it should be implemented.  But it makes this change a bit more invasive and impactful:

http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

Pending time I'll work on it but any help is appreciated.

**Comment by rustyconover** [comment]
Follow this feature branch:

https://github.com/rustyconover/net-amazon-s3/tree/feature-authv4

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
