### ISSUE TITLE
Please restore the original Changes file format

### ISSUE THREAD

**Issue by karenetheridge** [pfig/net-amazon-s3#66]
This file:
https://metacpan.org/changes/release/PFIG/Net-Amazon-S3-0.60

is infinitely easier to read and understand than this:
https://metacpan.org/changes/distribution/Net-Amazon-S3

It is much harder to find the place at which the last release happened -- indeed there are no release markers at all! -- and there is a lot of content that is meaningless to the end-user not familiar with the code. "Merge pull request #6" doesn't tell me anything about what the change actually contains or how it affects the behaviour of the code.

**Comment by rustyconover** [comment]
I'll accept the blame for this change.

The release before 0.80 was almost a year old and very stale.  Just look at the number of forks to fix one enum bug with Moose.  I had an open PR for almost a year and Pedro couldn't merge it, so eventually I got the co-maintainership bit after gathering community support and put 0.80 to CPAN as the first release and I switched to using the Git change log format.

As you can imagine a year is a long time to accumulate changes, and while I think the change format can be markedly improved the switch to using git commit messages as change messages I believe is better for contributors and users. 

If you know of an improvement rather than keeping a manual changes file I'm eager to learn.

**Comment by kentfredric** [comment]
The largest probable cause for that issue last I saw it is the "tag version" regex not matching the tags you have, or not fetching the tags so that they can be included.

Having the version tags in the right places in the log improve it substantially, but the log itself is still horrible from an end user perspective.

**Comment by kentfredric** [comment]
Also:

> the switch to using git commit messages as change messages I believe is better for contributors and users.

Generally, no. The only person whos life is made easier is the maintainer. Everyone elses lives is made harder.

When I look at somebody who has published a Changes file using git log, my first inclination is to close the tab and cease to care.

Usually, if I'm looking at the changes, I want a **summarised** set of changes oriented for the consumer. Not the nitty gritty details of when you tidied your code, removed trailing whitespace, fixed travis testing bugs, changed flow control inside a specific function, etc, etc.

As such, commit logs made with git like this are bad for users. I would literally prefer a missing change log to a git log, because I click the "Changes" link  on metacpan, expecting to have some changes I can peruse, and then get disappointed with a bunch of rubbish that no sense can be made from.

The only way using a git based changes log can be useful to end consumers as-is without some sort of commit filtering mechanism being implemented is by being incredibly restrictive about what you commit such that the git log itself is perfect, and commits like:

> Add gitignore 
> Bump to version 0.80 for new CPAN release, change repo references.
>  Fix typo 
> Merge branch 'iam_roles' into best-merge 
> fix synopsis for s3cl sync_up 

Simply do not happen. Because those things, literally nobody cares about.

And that level of control is rare and painful and I really do not expect anyone to be able to reasonably pull it off.

The best thing in the log is things like `Remove broken bucket as hostname detection code` and the rest of that message, that detail has to go *somewhere*, but the summarized changes log is not that place.

It would be better to have simply the abstract of that change, and not the body, and then have a detail view somewhere else for the people who care.

**Comment by dolmen** [comment]
A git log is just awful.
Git commit messages are for the developers of the distribution. And anyone interested can see them directly in the repository as it is public: no need to put it in CHANGES.
The CHANGES file is for users of the distribution. We read it to see important changes, to decide if it is worth using, or once using it if it is worth upgrading after a new release. Downstream modules authors read it to decide if they must require or recommend their users to upgrade.
Different users need different views of the same information.

**Comment by dolmen** [comment]
When picking a CPAN module, the CHANGES file is the first thing I look at. It immediately tells me how the distribution is maintained: what frequency for releases, how often bugs are fixed (which indicates that the dist has users and that the maintainers cares), how careful is the maintainer (dev releases?). It is more important to know that if I report an issue or submit a patch someone will care about it, than to know that the distribution has no bugs.

A VCS log in CHANGES immediately tells me that the maintainer is lazy. He doesn't want to talk to its users. So I should go elsewhere.

**Comment by rustyconover** [comment]
Thanks for elucidating the benefits of the traditional Changes file.  Expect me to do better in the future.

**Comment by karenetheridge** [comment]
@kentnl @dolmen I couldn't have said it better :) :+1: 

(The bottom line is that updating Changes is something that needs to be done manually - either just before a release, or just after merging a major feature.. there's no good way to automate it, because it needs to be phrased from the pespective of the user, and commit messages are oriented to the developer. And it's hard, because Changes entries are form of documentation, and we'd all rather write code than docs.) :)

**Comment by ranguard** [comment]
@rustyconover Please also realise that the fact you have taken on a module that REALLY needs help and has been stuck for over a year, means you can ignore everyone else and just work on the code. *_If_* you have time `Changes` nicely formatted are great, but getting bugs fixed is FAR more important than anything else IMHO. Your work on this is greatly appreciated.

**Comment by kentfredric** [comment]
> means you can ignore everyone else and just work on the code

I have to disagree. If you're working on an important module, which has a lot of consumers, the nature of _any_ change you make and the visibility of that change in a way consumers can understand is _incredibly_ important, if not more important than the code itself.

When working with maintainer pants on, your goal is

1. Don't change anything
2. Avoid changing anything unless you're fixing bugs
3. When changing things: Make it perfectly clear what was changed to consumers so they can justify upgrading.
4. When changing things, make it perfectly clear of any behavioural change a user will get when upgrading.
5. When potentially backwards-breaking changes are made, 3) and 4) are doubly important.

You need to sell users on your changes. And when things change for them, they need a quick way to be able to work out why.

A lucid changes file does these things and more.

And you should be listening to your consumers, because you're writing code that their code depends on.

I'm not exactly attempting to tell you what you *must* do, these are just our strongest recommendations / best practices that we've worked out and found to be "good" and generally, a good changelog effectively improves the quality of distribution it is in in significant ways for a consumer.

**Comment by ranguard** [comment]
@kentfredric you are right, I phrased it badly...

Having been watching this repo for years and seeing dozens of people getting bitten buy bugs again and again, that are already fixed in pull requests languishing without merge or release - I want @rustyconover to know that his work is appreciated.  I know you and @karenetheridge are helping with best practices and guidance, I just don't want @rustyconover  to get discouraged before he gets to do more cleanups.

**Comment by kentfredric** [comment]
>  I just don't want @rustyconover to get discouraged before he gets to do more cleanups.

+1. We're here to help. And your contributions are highly valued =).

**Comment by karenetheridge** [comment]
Yes, we definitely don't want to come across as "you're wrong and you're doing it wrong and we wish you hadn't done anything" -- totally the opposite.  I'm absolutely thrilled that this distribution is being maintained again -- this morning I just upgraded $work code to use 0.80 and removed our local patches, and everything is working great!

**Comment by rustyconover** [comment]
@karenetheridge thats the plan, I don't plan on any breaking changes or user visible API changes only bug fixes and some under the covers enhancements

The roadmap I see:

1. Move to AWS signatures v4 so that the module will work in Frankfurt.  No user visible changes.
2. Allow scalar references to be passed so people using older perl's won't be copying huge data when they set new keys.  But this is a lower priority since newer perl's already make this optimization.  Again no breaking user facing changes.
3. Fix any bugs that shake out in the mean time.

**Comment by rustyconover** [comment]
@karenetheridge Please see:

https://github.com/rustyconover/net-amazon-s3/blob/master/CHANGES

Will be included in next release.

**Comment by karenetheridge** [comment]
@rustyconover woohoo!!! +:100: :dancers:

**Comment by dolmen** [comment]
:clap:
